server:
  port: 8084
  
spring:
  application:
    name: consumer2
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
  instance:
    metadata-map:
      instanceId: ${spring:application:name}:${server:port}