server:
  port: 8081
  
spring:
  application:
    name: zuul-apigateway
    
zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 2000
  routes:
    consumer1:
      path: /con1/**
    consumer2:
      path: /con2/**
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
  instance:
    metadata-map:
      instanceId: ${spring:application:name}:${server:port}
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000 
          
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000