server:
  port: 8081
  
spring:
  application:
    name: zuul-apigateway
    
zuul:
  routes:
    consumer1:
      path: /con1/**
    consumer2:
      path: /con2/**
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
  instance:
    metadata-map:
      instanceId: ${spring:application:name}:${server:port}